[alias]
# Desktop client with GUI
cl = "run -- client -c 1"
# Desktop server
sv = "run -- server"
# Host-client (both)
hc = "run -- host-client"
# Enable HTTP asset IO
cl-http = "run --features http_assets -- client -c 1"
sv-http = "run --features http_assets -- server" 